todoSubject_use_restfulAPI/todoSubject/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo_main.urls')),
    path('index/', include('todo_main.urls')),
    path('home/', include('todo_main.urls')),

    # board app
    path('board/', include('todo_board.urls')),
]

todoSubject_use_restfulAPI/todo_board/urls.py
from django.conf.urls import url, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'todo_board'

urlpatterns = [
    url(r'^$', views.Todo_board.as_view(), name='todo_board'),
    url(r'^insert/$', views.check_post, name='todo_board_insert'),
    url(r'^save_prioirity/$', views.check_post, name='todo_board_save_priority'),
    url(r'^is_complete/$', views.check_post, name='todo_board_is_complete'),
    url(r'^is_non_complete/$', views.check_post, name='todo_board_is_non_complete'),
    url(r'^(?P<pk>[0-9]+)/detail/$', views.Todo_board_detail.as_view(), name='todo_board_detail'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.Todo_board_update.as_view(), name='todo_board_update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.check_post, name='todo_board_delete'),
    url(r'^(?P<pk>[0-9]+)/delete_complete/$', views.check_post, name='todo_board_delete_complete'),


    #url(r'^(?P<pk>[0-9]+)/delete/$', views.Todo_board_delete.as_view(), name='todo_board_delete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todoSubject_use_restfulAPI/todo_main/urls.py
from django.conf.urls import url, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'todo_main'

urlpatterns = [
    url(r'^$', views.Todo_main.as_view(), name='todo_main'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todoSubject_use_restfulAPI/todo_board/models.py
from django.db import models
from django.db.models import Max
# Create your models here.
class ProjectCode(models.Model):
    pcode = models.CharField(db_column='PCODE', primary_key=True, max_length=4)
    pname = models.CharField(db_column='PNAME', max_length=100)

    class Meta:
        managed = False
        db_table = 'project_code'

class TodoList(models.Model):
    no = models.AutoField(db_column='NO', primary_key=True)
    pcode = models.CharField(db_column='PCODE', max_length=4)
    user_id = models.CharField(db_column='USER_ID', max_length=50, blank=True, null=True)
    title = models.CharField(db_column='TITLE', max_length=200, blank=True, null=True)
    content = models.CharField(db_column='CONTENT', max_length=1000, blank=True, null=True)
    is_complete = models.IntegerField(db_column='IS_COMPLETE', blank=True, null=True)
    priority = models.IntegerField(db_column='PRIORITY', blank=True, null=True)
    end_date = models.DateField(db_column='END_DATE', blank=True, null=True)

    def todo_save(self):
        self.is_complete = 0
        if TodoList.objects.all().aggregate(Max('priority'))['priority__max'] is None : self.priority = 1
        else : self.priority = int(TodoList.objects.latest('priority').priority) + 1
        self.pcode = 1
        self.user_id = 'guest'
        self.save()

    def todo_update_is_complete(self, complete):
        self.is_complete = complete
        self.save()

    class Meta:
        managed = False
        db_table = 'todo_list'

todoSubject_use_restfulAPI/todo_board/forms.py
from django import forms
from .models import TodoList

class DateInput(forms.DateInput):
    input_type = 'date'

class TodoForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ('title', 'content', 'end_date')
        widgets = {
            'end_date' : DateInput()
        }

todoSubject_use_restfulAPI/todo_board/views.py
from django.shortcuts import render, redirect
from .models import TodoList
from .forms import TodoForm
from .get_data import get_data
from django.views import generic
from django.http import JsonResponse
from datetime import datetime, timedelta
import json

#board view
class Todo_board(generic.TemplateView):
    def get(self, request, *args, **kwargs):
        datas = get_data("list")
        todo_list_no_endDate, todo_list_endDate_non_complete, todo_list_endDate_complete, close_end_day, over_end_day = [],[],[],[],[]
        for data in datas:
            if data['end_date'] is None and data['is_complete'] == 0: todo_list_no_endDate.append(data)
            elif data['end_date'] is not None and data['is_complete'] == 0: todo_list_endDate_non_complete.append(data)
            elif data['is_complete'] == 1 : todo_list_endDate_complete.append(data)
        todo_list_no_endDate = sorted(todo_list_no_endDate, key=lambda x: x['priority'] if x['priority'] is not None else 0, reverse=False)
        todo_list_endDate_non_complete = sorted(todo_list_endDate_non_complete, key=lambda x: x['priority'] if x['priority'] is not None else 0, reverse=False)
        todo_list_endDate_complete = sorted(todo_list_endDate_complete, key=lambda x: x['end_date'] if x['end_date'] is not None else '0000-00-00', reverse=True)

        template_name = 'todo_board/todo_board_list.html'
        today = datetime.now()
        # deadline is close
        close_end_day = []
        #over time
        over_end_day = []
        for i in todo_list_endDate_non_complete:
            e_day = str(i["end_date"]).split("-")
            end_day = datetime(int(e_day[0]), int(e_day[1]), int(e_day[2]))
            if (end_day - today).days < -1: over_end_day.append(i["title"])
            if (end_day - today).days >= -1 and (end_day - today).days < 3: close_end_day.append(i["title"])
        return render(request, template_name, {"todo_list_endDate_non_complete": todo_list_endDate_non_complete, "todo_list_endDate_complete": todo_list_endDate_complete, "todo_list_no_endDate": todo_list_no_endDate, 'close_end_day': close_end_day, 'over_end_day':over_end_day})

#todo_detail view
class Todo_board_detail(generic.DetailView):
    def get(self, request, *args, **kwargs):
        datas = {
            'pk': self.kwargs['pk']
        }
        datas = get_data("detail", datas=datas)
        return render(self.request, 'todo_board/todo_board_detail.html', {"todo_list": datas})

#todo_update view
class Todo_board_update(generic.UpdateView):
    model = TodoList
    form_class = TodoForm
    template_name = 'todo_board/todo_board_update.html'
    success_url = '/board/'
    def form_valid(self, form):
        datas = {
            'title': self.request.POST.get('title'),
            'content': self.request.POST.get('title'),
            'end_date': self.request.POST.get('end_date'),
            'pk' : self.kwargs['pk']
        }
        datas = get_data("update", datas=datas)
        return render(self.request, 'todo_board/todo_board_success.html', {"message": datas})


# when write new todo_list
# post -> when click "save"
# get -> just view a template
def check_post(request, pk=None):
    template_name = 'todo_board/todo_board_success.html'
    # when POST
    if request.method == "POST":
        # when data isnert
        if str(request.path).split("/board/")[1].split("/")[0] == "insert":
            form = TodoForm(request.POST)
            if form.is_valid():
                if len(request.POST.get('title')) < 2:
                    datas = "제목은 2글자 이상으로 입력해주세요!"
                else:
                    datas = {
                        'title':request.POST.get('title'),
                        'content' : request.POST.get('content'),
                        'end_date' : request.POST.get('end_date'),
                        'is_complete': 0
                    }
                    datas = get_data("create", datas=datas)
                return render(request, template_name, {"message": datas})

        # when data save priority
        elif str(request.path).split("/board/")[1].split("/")[0] == "save_prioirity":
            todo_list = json.loads(request.POST['todo_dict'])
            for key, value in todo_list.items():
                if key == "None" : continue
                # too slow..
                datas = get_data("detail", datas={'pk': key})
                datas['priority'] = value
                datas['pk'] = datas.pop('no')
                datas = get_data("update", datas=datas)
            return JsonResponse({'text': '저장되었습니다.'})
        #when check checkbox to complete
        elif str(request.path).split("/board/")[1].split("/")[0] == "is_complete":
            pk = request.POST['data']
            return_value = checkbox_event(pk, True)
            return JsonResponse(return_value)
        #when uncheck checkbox complete
        elif str(request.path).split("/board/")[1].split("/")[0] == "is_non_complete":
            pk = request.POST['data']
            return_value = checkbox_event(pk, False)
            return JsonResponse(return_value)
    # GET
    else:
        if str(request.path).split("/board/")[1].split("/")[0] == "insert":
            template_name = 'todo_board/todo_board_insert.html'
            form = TodoForm
            return render(request, template_name, {"form" : form})
        # confirm delete
        if str(request.path).split("/board/")[1].split("/")[1] == "delete":
            datas = get_data("detail", datas={'pk':pk})
            template_name = 'todo_board/todolist_confirm_delete.html'
            return render(request, template_name, {'todo_list':datas})
        # delete
        if str(request.path).split("/board/")[1].split("/")[1] == "delete_complete":
            datas = get_data("delete", datas={'pk': pk})
            return render(request, template_name, {'message':datas})

def checkbox_event(pk, is_check):
    datas = get_data("detail", datas={'pk': pk})
    datas['pk'] = datas.pop('no')
    if is_check == True:
        datas['is_complete'] = 1
    else:
        datas['is_complete'] = 0
    datas = get_data("update", datas=datas)
    return_value = {'text': '저장되었습니다.'}
    return return_value

todoSubject_use_restfulAPI/todo_board/templates/todo_board/todo_board_detail.html
{% extends 'todo_main/common/header.html' %}
{% load staticfiles %}
{% block main %}
<section id="blog">
  <div class="container">
    <table class="table table-bordered">
          <thead>
            <tr>
              <th>제목</th>
              <th>내용</th>
              <th>마감일</th>
            </tr>
          </thead>
        <tbody>
          <tr>
            <td>{{ todo_list.title }}</td>
            <td>{{ todo_list.content }}</td>
            <td>{{ todo_list.end_date }}</td>
          </tr>
        </tbody>
    </table>
    <button type="button" class="btn btn-primary" onclick="location.href='{% url 'todo_board:todo_board_update' pk=todo_list.no %} '">수정</button>
    <button type="button" class="btn btn-primary" onclick="location.href='{% url 'todo_board:todo_board_delete' pk=todo_list.no %} '">삭제</button>
  </div>
</section>

{% endblock main %}

todoSubject_use_restfulAPI/todo_board/templates/todo_board/todo_board_insert.html
{% extends 'todo_main/common/header.html' %}
{% load staticfiles %}
{% block main %}

<div class="col-md-12">
    <div class="container">
        <form method="POST" class="post-form" action="{% url 'todo_board:todo_board_insert' %}">
           {%csrf_token%}

           {{form.as_p}}
           <button type="submit" class="save btn btn-default">Save</button>
       </form>
    </div>

</div>

{% endblock main %}

todoSubject_use_restfulAPI/todo_board/templates/todo_board/todo_board_list.html
{% extends 'todo_main/common/header.html' %}
{% load staticfiles %}
{% block main %}

<div class="alert alert-info">
    <strong>마감이 지난 일정!</strong> {{ over_end_day }}
</div>
<div class="alert alert-info">
    <strong>마감이 가까운 일정!</strong> {{ close_end_day }}
</div>
<div class="col-md-4">
    <div class="container">
        <h2>기한 있는 일정</h2><br>
        <div id="todo_list_endDate" class="list-group col">
            {% for list in todo_list_endDate_non_complete %}
            <div class="list-group-item" div_pk={{list.no}} priority={{list.priority}}><input type="checkbox" pk={{list.no}} name="end_non_complete" value={{list.title}}> <a href="{% url 'todo_board:todo_board_detail' pk=list.no %}">{{list.title}}</a><p>{{list.end_date}}</p></div>
            {% endfor %}
        </div>
    </div>
</div>
<div class="col-md-4">
    <div class="container">
        <h2>기한 없는 일정</h2><br>
        <div id="todo_list_no_endDate" class="list-group col">
        {% with end_date="마감일 없음" %}
            {% for list in todo_list_no_endDate %}
            <div class="list-group-item" div_pk={{list.no}}><input type="checkbox" pk={{list.no}} name="no_endDate_non_complete" value={{list.title}}> <a href="{% url 'todo_board:todo_board_detail' pk=list.no %}">{{list.title}}</a><p>{{end_date}}</p></div>
            {% endfor %}
        {% endwith %}
        </div>
    </div>
</div>

<div class="col-md-4">
    <div class="container">
        <h2>마감 된 일정</h2><br>
        <div class="list-group col">
            {% for list in todo_list_endDate_complete %}
            <div class="list-group-item list-group-item-success" div_pk={{list.priority}}><input type="checkbox" pk={{list.no}} name="complete" value={{list.title}}> <a href="{% url 'todo_board:todo_board_detail' pk=list.no %}">{{list.title}}</a><p>{{list.end_date}}</p></div>
            {% endfor %}
        </div>
    </div>
</div>

<div class="col-md-12">
      <button type="button" class="btn btn-primary" onclick="location.href='{% url 'todo_board:todo_board_insert' %} '">
            일정추가
      </button>
      <button type="button" class="btn btn-primary" onclick="prioirty_save()">
            우선순위 저장
      </button>
</div>

{% endblock main %}

todoSubject_use_restfulAPI/todo_board/templates/todo_board/todo_board_success.html
<script>
    message = "{{ message }}";
    alert(message);
    window.location.href = "{% url 'todo_board:todo_board' %}"
</script>

todoSubject_use_restfulAPI/todo_board/templates/todo_board/todo_board_update.html
{% extends 'todo_main/common/header.html' %}
{% load staticfiles %}
{% block main %}
<section id="blog">
  <div class="container">
   <form method="POST" class="post-form">
       {%csrf_token%}

       {{form.as_p}}
       <input type="submit" class="save btn btn-default" value="Update"></input>
   </form>
  </div>
</section>

{% endblock main %}

todoSubject_use_restfulAPI/todo_board/templates/todo_board/todolist_confirm_delete.html
{% extends 'todo_main/common/header.html' %}
{% load staticfiles %}
{% block main %}

<section id="blog">
  <div class="container">
   <form method="POST" class="post-form">
       {%csrf_token%}

       <p>정말로 {{ todo_list.title }} 일정을 삭제하시나요?</p>
       <button type="button" class="btn btn-primary" onclick="location.href='{% url 'todo_board:todo_board_delete_complete' pk=todo_list.no %} '">
            삭제
      </button>
   </form>
  </div>
</section>

{% endblock main %}