todoSubject/todoSubject/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo_main.urls')),
    path('index/', include('todo_main.urls')),
    path('home/', include('todo_main.urls')),

    # board app
    path('board/', include('todo_board.urls')),
]

todoSubject/todo_board/urls.py
from django.conf.urls import url, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'todo_board'

urlpatterns = [
    url(r'^$', views.Todo_board.as_view(), name='todo_board'),
    url(r'^insert/$', views.check_post, name='todo_board_insert'),
    url(r'^save_prioirity/$', views.check_post, name='todo_board_save_priority'),
    url(r'^is_complete/$', views.check_post, name='todo_board_is_complete'),
    url(r'^is_non_complete/$', views.check_post, name='todo_board_is_non_complete'),
    url(r'^(?P<pk>[0-9]+)/detail/$', views.Todo_board_detail.as_view(), name='todo_board_detail'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.Todo_board_update.as_view(), name='todo_board_update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.Todo_board_delete.as_view(), name='todo_board_delete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todoSubject/todo_main/urls.py
from django.conf.urls import url, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'todo_main'

urlpatterns = [
    url(r'^$', views.Todo_main.as_view(), name='todo_main'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todoSubject/todo_board/models.py
from django.db import models
from django.db.models import Max
# Create your models here.
class ProjectCode(models.Model):
    pcode = models.CharField(db_column='PCODE', primary_key=True, max_length=4)
    pname = models.CharField(db_column='PNAME', max_length=100)

    class Meta:
        managed = False
        db_table = 'project_code'

class TodoList(models.Model):
    no = models.AutoField(db_column='NO', primary_key=True)
    pcode = models.CharField(db_column='PCODE', max_length=4)
    user_id = models.CharField(db_column='USER_ID', max_length=50, blank=True, null=True)
    title = models.CharField(db_column='TITLE', max_length=200, blank=True, null=True)
    content = models.CharField(db_column='CONTENT', max_length=1000, blank=True, null=True)
    is_complete = models.IntegerField(db_column='IS_COMPLETE', blank=True, null=True)
    priority = models.IntegerField(db_column='PRIORITY', blank=True, null=True)
    end_date = models.DateField(db_column='END_DATE', blank=True, null=True)

    def todo_save(self):
        self.is_complete = 0
        if TodoList.objects.all().aggregate(Max('priority'))['priority__max'] is None : self.priority = 1
        else : self.priority = int(TodoList.objects.latest('priority').priority) + 1
        self.pcode = 1
        self.user_id = 'guest'
        self.save()

    def todo_update_is_complete(self, complete):
        self.is_complete = complete
        self.save()

    class Meta:
        managed = False
        db_table = 'todo_list'

todoSubject/todo_main/models.py
from django.db import models

# Create your models here.

todoSubject/todo_board/forms.py
from django import forms
from .models import TodoList

class DateInput(forms.DateInput):
    input_type = 'date'

class TodoForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ('title', 'content', 'end_date')
        widgets = {
            'end_date' : DateInput()
        }

todoSubject/todo_board/views.py
from django.shortcuts import render, redirect
from .models import TodoList
from .forms import TodoForm
from django.views import generic
from django.http import JsonResponse
from datetime import datetime, timedelta
import json

#board view
class Todo_board(generic.TemplateView):
    def get(self, request, *args, **kwargs):
        #Reserved.objects.filter(client=client_id).order_by('-check_in')
        template_name = 'todo_board/todo_board_list.html'
        #기한 없는 일정, 마감 안된 애들
        todo_list_no_endDate = TodoList.objects.all().filter(end_date__isnull=True, is_complete=0).order_by('priority')
        #기한 있고, 마감이 안된 애들
        todo_list_endDate_non_complete = TodoList.objects.all().filter(end_date__isnull=False, is_complete=0).order_by('priority')
        #마김이 된 애들
        todo_list_endDate_complete = TodoList.objects.all().filter(is_complete=1).order_by('end_date')
        today = datetime.now()
        # deadline is close
        close_end_day = []
        #over time
        over_end_day = []
        for i in todo_list_endDate_non_complete:
            e_day = str(i.end_date).split("-")
            end_day = datetime(int(e_day[0]), int(e_day[1]), int(e_day[2]))
            if (end_day - today).days < -1: over_end_day.append(i.title)
            if (end_day - today).days >= -1 and (end_day - today).days < 3: close_end_day.append(i.title)
        return render(request, template_name, {"todo_list_endDate_non_complete": todo_list_endDate_non_complete, "todo_list_endDate_complete": todo_list_endDate_complete, "todo_list_no_endDate": todo_list_no_endDate, 'close_end_day': close_end_day, 'over_end_day':over_end_day})

#todo_detail view
class Todo_board_detail(generic.DetailView):
    model = TodoList
    template_name = 'todo_board/todo_board_detail.html'
    context_object_name = 'todo_list'

#todo_update view
class Todo_board_update(generic.UpdateView):
    model = TodoList
    form_class = TodoForm
    template_name = 'todo_board/todo_board_update.html'
    success_url = '/board/'

    def form_valid(self, form):
        form.save()
        return render(self.request, 'todo_board/todo_board_success.html', {"message": "일정을 업데이트 했습니다"})

# todo_delete view
class Todo_board_delete(generic.DeleteView):
    model = TodoList
    success_url = '/board/'
    context_object_name = 'todo_list'

# when write new todo_list
# post -> when click "save"
# get -> just view a template
def check_post(request):
    template_name = 'todo_board/todo_board_success.html'
    if request.method == "POST":
        if str(request.path).split("/board/")[1].split("/")[0] == "insert":
            form = TodoForm(request.POST)
            if form.is_valid():
                message = "일정을 추가하였습니다."
                if len(request.POST.get('title')) < 2:
                    message = "제목은 2글자 이상으로 입력해주세요!"
                else:
                    todo = form.save(commit=False)
                    todo.todo_save()
                return render(request, template_name, {"message": message})
        elif str(request.path).split("/board/")[1].split("/")[0] == "save_prioirity":
            todo_list = json.loads(request.POST['todo_dict'])
            for key, value in todo_list.items():
                if key == "None" : continue
                todo_selected = TodoList.objects.get(pk=key)
                todo_selected.priority = value
                todo_selected.save()
            return JsonResponse({'text': '저장되었습니다.'})
        elif str(request.path).split("/board/")[1].split("/")[0] == "is_complete":
            pk = request.POST['data']
            return_value = checkbox_event(pk, True)
            return JsonResponse(return_value)
        elif str(request.path).split("/board/")[1].split("/")[0] == "is_non_complete":
            pk = request.POST['data']
            return_value = checkbox_event(pk, False)
            return JsonResponse(return_value)
    else:
        template_name = 'todo_board/todo_board_insert.html'
        form = TodoForm
        return render(request, template_name, {"form" : form})

def checkbox_event(pk, is_check):
    todo_selected = TodoList.objects.get(pk=pk)
    if is_check == True:
        todo_selected.is_complete = 1
        todo_selected.priority = None
    else :
        todo_selected.is_complete = 0
    todo_selected.save()
    return_value = {'text': '저장되었습니다.'}
    return return_value

todoSubject/todo_main/views.py
from django.shortcuts import render, redirect

from django.views import View
from django.views import generic

class Todo_main(generic.TemplateView):
    def get(self, request, *args, **kwargs):
        template_name = 'todo_main/index.html'
        return render(request, template_name)

todoSubject/todo_board/templates/todo_board/todo_board_detail.html
{% extends 'todo_main/common/header.html' %}
{% load staticfiles %}
{% block main %}
<section id="blog">
  <div class="container">
    <table class="table table-bordered">
          <thead>
            <tr>
              <th>제목</th>
              <th>내용</th>
              <th>마감일</th>
            </tr>
          </thead>
        <tbody>
          <tr>
            <td>{{ todo_list.title }}</td>
            <td>{{ todo_list.content }}</td>
            <td>{{ todo_list.end_date }}</td>
          </tr>
        </tbody>
    </table>
    <button type="button" class="btn btn-primary" onclick="location.href='{% url 'todo_board:todo_board_update' pk=todo_list.pk %} '">수정</button>
    <button type="button" class="btn btn-primary" onclick="location.href='{% url 'todo_board:todo_board_delete' pk=todo_list.pk %} '">삭제</button>
  </div>
</section>

{% endblock main %}

todoSubject/todo_board/templates/todo_board/todo_board_insert.html
{% extends 'todo_main/common/header.html' %}
{% load staticfiles %}
{% block main %}

<div class="col-md-12">
    <div class="container">
        <form method="POST" class="post-form" action="{% url 'todo_board:todo_board_insert' %}">
           {%csrf_token%}

           {{form.as_p}}
           <button type="submit" class="save btn btn-default">Save</button>
       </form>
    </div>

</div>

{% endblock main %}

todoSubject/todo_board/templates/todo_board/todo_board_list.html
{% extends 'todo_main/common/header.html' %}
{% load staticfiles %}
{% block main %}

<div class="alert alert-info">
    <strong>마감이 지난 일정!</strong> {{ over_end_day }}
</div>
<div class="alert alert-info">
    <strong>마감이 가까운 일정!</strong> {{ close_end_day }}
</div>
<div class="col-md-4">
    <div class="container">
        <h2>기한 있는 일정</h2><br>
        <div id="todo_list_endDate" class="list-group col">
            {% for list in todo_list_endDate_non_complete %}
            <div class="list-group-item" div_pk={{list.no}} priority={{list.priority}}><input type="checkbox" pk={{list.no}} name="end_non_complete" value={{list.title}}> <a href="{% url 'todo_board:todo_board_detail' pk=list.no %}">{{list.title}}</a><p>{{list.end_date}}</p></div>
            {% endfor %}
        </div>
    </div>
</div>
<div class="col-md-4">
    <div class="container">
        <h2>기한 없는 일정</h2><br>
        <div id="todo_list_no_endDate" class="list-group col">
        {% with end_date="마감일 없음" %}
            {% for list in todo_list_no_endDate %}
            <div class="list-group-item" div_pk={{list.no}}><input type="checkbox" pk={{list.no}} name="no_endDate_non_complete" value={{list.title}}> <a href="{% url 'todo_board:todo_board_detail' pk=list.no %}">{{list.title}}</a><p>{{end_date}}</p></div>
            {% endfor %}
        {% endwith %}
        </div>
    </div>
</div>

<div class="col-md-4">
    <div class="container">
        <h2>마감 된 일정</h2><br>
        <div class="list-group col">
            {% with end_date="마감일 없음" %}
                {% for list in todo_list_endDate_complete %}
                    {% if list.end_date == None %}
                        <div class="list-group-item list-group-item-success" div_pk={{list.priority}}><input type="checkbox" pk={{list.no}} name="complete" value={{list.title}}> <a href="{% url 'todo_board:todo_board_detail' pk=list.no %}">{{list.title}}</a><p>{{end_date}}</p></div>
                    {% else %}
                        <div class="list-group-item list-group-item-success" div_pk={{list.priority}}><input type="checkbox" pk={{list.no}} name="complete" value={{list.title}}> <a href="{% url 'todo_board:todo_board_detail' pk=list.no %}">{{list.title}}</a><p>{{list.end_date}}</p></div>
                    {% endif %}
                {% endfor %}
            {% endwith %}
        </div>
    </div>
</div>

<div class="col-md-12">
      <button type="button" class="btn btn-primary" onclick="location.href='{% url 'todo_board:todo_board_insert' %} '">
            일정추가
      </button>
      <button type="button" class="btn btn-primary" onclick="prioirty_save()">
            *우선순위 저장
      </button>
      <p>* 마우스 드래그로 우선순위 변경이 가능합니다</p>
</div>

{% endblock main %}

todoSubject/todo_board/templates/todo_board/todo_board_success.html
<script>
    message = "{{ message }}";
    alert(message);
    window.location.href = "{% url 'todo_board:todo_board' %}"
</script>

todoSubject/todo_board/templates/todo_board/todo_board_update.html
{% extends 'todo_main/common/header.html' %}
{% load staticfiles %}
{% block main %}
<section id="blog">
  <div class="container">
   <form method="POST" class="post-form">
       {%csrf_token%}

       {{form.as_p}}
       <input type="submit" class="save btn btn-default" value="Update"></input>
   </form>
  </div>
</section>

{% endblock main %}

todoSubject/todo_board/templates/todo_board/todolist_confirm_delete.html
{% extends 'todo_main/common/header.html' %}
{% load staticfiles %}
{% block main %}

<section id="blog">
  <div class="container">
   <form method="POST" class="post-form">
       {%csrf_token%}

       <p>정말로 {{ todo_list.title }} 일정을 삭제하시나요?</p>
       <input type="submit" class="save btn btn-default" value="Confirm"/>
   </form>
  </div>
</section>

{% endblock main %}

todoSubject/todo_main/templates/todo_main/common/header.html
<html lang="ko">

    {% load staticfiles %}
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!--Fontawesom-->
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

        <!--Animated CSS-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/animate.min.css' %}">

        <!-- Bootstrap -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <!--Bootstrap Carousel-->
        <link type="text/css" rel="stylesheet" href="{% static 'css/carousel.css' %}" />

        <link rel="stylesheet" href="{% static 'css/isotope/style.css' %}">

        <!--Main Stylesheet-->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <!--Responsive Framework-->
        <link href="{% static 'css/responsive.css' %}" rel="stylesheet">

      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
        <script>



        </script>
		<style type="text/css">
            #container {
                min-width: 310px;
                max-width: 800px;
                height: 400px;
                margin: 0 auto
            }
            input[type=text] {
              width: 100%;
              padding: 12px 20px;
              margin: 8px 0;
              box-sizing: border-box;
            }

            .list-group-item{
                width : 40%;
            }
		</style>


    </head>
    <body>
        <nav class="navbar navbar-inverse">
          <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand" href="#"></a>
            </div>
            <ul class="nav navbar-nav">
              <li><a href="{% url 'todo_main:todo_main' %}">todo main</a></li>
              <li><a href="{% url 'todo_board:todo_board' %}">todo list</a></li>
            </ul>
          </div>
        </nav>
        {% block main %}

        {% endblock main %}
    </body>

    <script src="{% static 'js/Sortable.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
    <script>
        new Sortable(todo_list_endDate, {
            animation: 150,
            ghostClass: 'blue-background-class'
        });
        new Sortable(todo_list_no_endDate, {
            animation: 150,
            ghostClass: 'blue-background-class'
        });


    </script>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

    <script>
        function prioirty_save(){
            todo_list = $(".list-group-item");
            todo_dict = {}
            for(var i = 0 ; i < todo_list.length ; i++){
                todo_dict[todo_list[i].getAttribute("div_pk")] = i + 1
            }
            console.log(todo_dict);
            $.ajax({
              type: "POST",
              url: "{% url 'todo_board:todo_board_save_priority' %}",
              data: {'todo_dict': JSON.stringify(todo_dict), 'csrfmiddlewaretoken': '{{ csrf_token }}'},
              dataType: "json",
              success: function(response){
                console.log("성공");
                window.location.href = "{% url 'todo_board:todo_board' %}"
              },
              error: function(request, status, error){
                console.log("실패.");
              },
            });
        }
    </script>

    <script>
        completed = document.getElementsByName('complete');
        for(var i = 0; i < completed.length ; i++){
            completed[i].checked = true;
        }

        $("input[name*=complete]").change(function(){
            if($(this).is(":checked")){
                pk = $(this).attr("pk");
                $.ajax({
                  type: "POST",
                  url: "{% url 'todo_board:todo_board_is_complete' %}",
                  data: {'data': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                  dataType: "json",
                  success: function(response){
                    console.log("성공");
                    window.location.href = "{% url 'todo_board:todo_board' %}"
                  },
                  error: function(request, status, error){
                    console.log("실패.");
                  },
                });
            }
            //체크박스 해제
            else{
                pk = $(this).attr("pk");
                $.ajax({
                  type: "POST",
                  url: "{% url 'todo_board:todo_board_is_non_complete' %}",
                  data: {'data': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                  dataType: "json",
                  success: function(response){
                    window.location.href = "{% url 'todo_board:todo_board' %}"
                  },
                  error: function(request, status, error){
                    console.log("실패.");
                  },
                });
            }
        });

    </script>
</html>

todoSubject/todo_main/templates/todo_main/index.html
{% extends 'todo_main/common/header.html' %}
{% load staticfiles %}
{% block main %}

<div class="container">
  <div class="">
    <h1>안녕하세요</h1>
    <p>python django를 활용한 todo 웹 개발 입니다. <br> 도움이 되셨다면 깃 스타를 눌러주세요! 저에게 큰 힘이 됩니다.</p>
    <br>
    <p> 깃허브 : <a href="https://github.com/lsjsj92/django_todo_app">https://github.com/lsjsj92/django_todo_app</a></p>
  </div>
</div>

{% endblock main %}